
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.enhancing.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.enhancing.block.WeatheredCutCopperVerticalSlabBlock;
import net.mcreator.enhancing.block.WaxedWeatheredCutCopperVerticalSlabBlock;
import net.mcreator.enhancing.block.WaxedOxidizedCutCopperVerticalSlabBlock;
import net.mcreator.enhancing.block.WaxedExposedCutCopperVerticalSlabBlock;
import net.mcreator.enhancing.block.WaxedCutCopperVerticalSlabBlock;
import net.mcreator.enhancing.block.WarpedVerticalSlabBlock;
import net.mcreator.enhancing.block.StoneVerticalSlabBlock;
import net.mcreator.enhancing.block.StoneBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.SpruceVerticalSlabBlock;
import net.mcreator.enhancing.block.SmoothStoneVerticalSlabBlock;
import net.mcreator.enhancing.block.SandstoneVerticalSlabBlock;
import net.mcreator.enhancing.block.RunedDeepslateBricksGammaOnBlock;
import net.mcreator.enhancing.block.RunedDeepslateBricksGammaOffBlock;
import net.mcreator.enhancing.block.RunedDeepslateBricksEtaOnBlock;
import net.mcreator.enhancing.block.RunedDeepslateBricksEtaOffBlock;
import net.mcreator.enhancing.block.RunedDeepslateBricksBetaOnBlock;
import net.mcreator.enhancing.block.RunedDeepslateBricksBetaOffBlock;
import net.mcreator.enhancing.block.RedSandstoneVerticalSlabBlock;
import net.mcreator.enhancing.block.RedNetherBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.QuartzVerticalSlabBlock;
import net.mcreator.enhancing.block.PurpurVerticalSlabBlock;
import net.mcreator.enhancing.block.PrismarineVerticalSlabBlock;
import net.mcreator.enhancing.block.PrismarineBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.PolishedGraniteVerticalSlabBlock;
import net.mcreator.enhancing.block.PolishedDioriteVerticalSlabBlock;
import net.mcreator.enhancing.block.PolishedDeepslateVerticalSlabBlock;
import net.mcreator.enhancing.block.PolishedBlackstoneVerticalSlabBlock;
import net.mcreator.enhancing.block.PolishedBlackstoneBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.PolishedAndesiteVerticalSlabBlock;
import net.mcreator.enhancing.block.OxidizedCutCopperVerticalSlabBlock;
import net.mcreator.enhancing.block.OakredrooftilesBlock;
import net.mcreator.enhancing.block.OakVerticalSlabBlock;
import net.mcreator.enhancing.block.NetherBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.MudBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.MossyStoneBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.MossyCobblestoneVerticalSlabBlock;
import net.mcreator.enhancing.block.MangroveVerticalSlabBlock;
import net.mcreator.enhancing.block.JungleVerticalSlabBlock;
import net.mcreator.enhancing.block.GraniteVerticalSlabBlock;
import net.mcreator.enhancing.block.ExposedCutCopperVerticalSlabBlock;
import net.mcreator.enhancing.block.EndStoneBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.DirtStairsBlock;
import net.mcreator.enhancing.block.DirtSlabBlock;
import net.mcreator.enhancing.block.DioriteVerticalSlabBlock;
import net.mcreator.enhancing.block.DeepslateTileVerticalSlabBlock;
import net.mcreator.enhancing.block.DeepslateBrickVerticalSlabBlock;
import net.mcreator.enhancing.block.DarkPrismarineVerticalSlabBlock;
import net.mcreator.enhancing.block.DarkOakVerticalSlabBlock;
import net.mcreator.enhancing.block.CutCopperVerticalSlabBlock;
import net.mcreator.enhancing.block.CrimsonVerticalSlabBlock;
import net.mcreator.enhancing.block.CobblestoneVerticalSlabBlock;
import net.mcreator.enhancing.block.CobbledDeepslateVerticalSlabBlock;
import net.mcreator.enhancing.block.CoalFurnaceBlock;
import net.mcreator.enhancing.block.BurntOutLanternBlock;
import net.mcreator.enhancing.block.BrickVerticalSlabBlock;
import net.mcreator.enhancing.block.BlackstoneVerticalSlabBlock;
import net.mcreator.enhancing.block.BirchVerticalSlabBlock;
import net.mcreator.enhancing.block.AndesiteVerticalSlabBlock;
import net.mcreator.enhancing.block.AcaciaVerticalSlabBlock;
import net.mcreator.enhancing.EnhancingMod;

public class EnhancingModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, EnhancingMod.MODID);
	public static final RegistryObject<Block> STONE_VERTICAL_SLAB = REGISTRY.register("stone_vertical_slab", () -> new StoneVerticalSlabBlock());
	public static final RegistryObject<Block> COBBLESTONE_VERTICAL_SLAB = REGISTRY.register("cobblestone_vertical_slab", () -> new CobblestoneVerticalSlabBlock());
	public static final RegistryObject<Block> OAK_VERTICAL_SLAB = REGISTRY.register("oak_vertical_slab", () -> new OakVerticalSlabBlock());
	public static final RegistryObject<Block> SPRUCE_VERTICAL_SLAB = REGISTRY.register("spruce_vertical_slab", () -> new SpruceVerticalSlabBlock());
	public static final RegistryObject<Block> BIRCH_VERTICAL_SLAB = REGISTRY.register("birch_vertical_slab", () -> new BirchVerticalSlabBlock());
	public static final RegistryObject<Block> JUNGLE_VERTICAL_SLAB = REGISTRY.register("jungle_vertical_slab", () -> new JungleVerticalSlabBlock());
	public static final RegistryObject<Block> ACACIA_VERTICAL_SLAB = REGISTRY.register("acacia_vertical_slab", () -> new AcaciaVerticalSlabBlock());
	public static final RegistryObject<Block> DARK_OAK_VERTICAL_SLAB = REGISTRY.register("dark_oak_vertical_slab", () -> new DarkOakVerticalSlabBlock());
	public static final RegistryObject<Block> MANGROVE_VERTICAL_SLAB = REGISTRY.register("mangrove_vertical_slab", () -> new MangroveVerticalSlabBlock());
	public static final RegistryObject<Block> CRIMSON_VERTICAL_SLAB = REGISTRY.register("crimson_vertical_slab", () -> new CrimsonVerticalSlabBlock());
	public static final RegistryObject<Block> WARPED_VERTICAL_SLAB = REGISTRY.register("warped_vertical_slab", () -> new WarpedVerticalSlabBlock());
	public static final RegistryObject<Block> SMOOTH_STONE_VERTICAL_SLAB = REGISTRY.register("smooth_stone_vertical_slab", () -> new SmoothStoneVerticalSlabBlock());
	public static final RegistryObject<Block> MOSSY_COBBLESTONE_VERTICAL_SLAB = REGISTRY.register("mossy_cobblestone_vertical_slab", () -> new MossyCobblestoneVerticalSlabBlock());
	public static final RegistryObject<Block> STONE_BRICK_VERTICAL_SLAB = REGISTRY.register("stone_brick_vertical_slab", () -> new StoneBrickVerticalSlabBlock());
	public static final RegistryObject<Block> MOSSY_STONE_BRICK_VERTICAL_SLAB = REGISTRY.register("mossy_stone_brick_vertical_slab", () -> new MossyStoneBrickVerticalSlabBlock());
	public static final RegistryObject<Block> ANDESITE_VERTICAL_SLAB = REGISTRY.register("andesite_vertical_slab", () -> new AndesiteVerticalSlabBlock());
	public static final RegistryObject<Block> POLISHED_ANDESITE_VERTICAL_SLAB = REGISTRY.register("polished_andesite_vertical_slab", () -> new PolishedAndesiteVerticalSlabBlock());
	public static final RegistryObject<Block> DIORITE_VERTICAL_SLAB = REGISTRY.register("diorite_vertical_slab", () -> new DioriteVerticalSlabBlock());
	public static final RegistryObject<Block> POLISHED_DIORITE_VERTICAL_SLAB = REGISTRY.register("polished_diorite_vertical_slab", () -> new PolishedDioriteVerticalSlabBlock());
	public static final RegistryObject<Block> GRANITE_VERTICAL_SLAB = REGISTRY.register("granite_vertical_slab", () -> new GraniteVerticalSlabBlock());
	public static final RegistryObject<Block> POLISHED_GRANITE_VERTICAL_SLAB = REGISTRY.register("polished_granite_vertical_slab", () -> new PolishedGraniteVerticalSlabBlock());
	public static final RegistryObject<Block> SANDSTONE_VERTICAL_SLAB = REGISTRY.register("sandstone_vertical_slab", () -> new SandstoneVerticalSlabBlock());
	public static final RegistryObject<Block> RED_SANDSTONE_VERTICAL_SLAB = REGISTRY.register("red_sandstone_vertical_slab", () -> new RedSandstoneVerticalSlabBlock());
	public static final RegistryObject<Block> BRICK_VERTICAL_SLAB = REGISTRY.register("brick_vertical_slab", () -> new BrickVerticalSlabBlock());
	public static final RegistryObject<Block> PRISMARINE_VERTICAL_SLAB = REGISTRY.register("prismarine_vertical_slab", () -> new PrismarineVerticalSlabBlock());
	public static final RegistryObject<Block> PRISMARINE_BRICK_VERTICAL_SLAB = REGISTRY.register("prismarine_brick_vertical_slab", () -> new PrismarineBrickVerticalSlabBlock());
	public static final RegistryObject<Block> DARK_PRISMARINE_VERTICAL_SLAB = REGISTRY.register("dark_prismarine_vertical_slab", () -> new DarkPrismarineVerticalSlabBlock());
	public static final RegistryObject<Block> NETHER_BRICK_VERTICAL_SLAB = REGISTRY.register("nether_brick_vertical_slab", () -> new NetherBrickVerticalSlabBlock());
	public static final RegistryObject<Block> RED_NETHER_BRICK_VERTICAL_SLAB = REGISTRY.register("red_nether_brick_vertical_slab", () -> new RedNetherBrickVerticalSlabBlock());
	public static final RegistryObject<Block> QUARTZ_VERTICAL_SLAB = REGISTRY.register("quartz_vertical_slab", () -> new QuartzVerticalSlabBlock());
	public static final RegistryObject<Block> PURPUR_VERTICAL_SLAB = REGISTRY.register("purpur_vertical_slab", () -> new PurpurVerticalSlabBlock());
	public static final RegistryObject<Block> END_STONE_BRICK_VERTICAL_SLAB = REGISTRY.register("end_stone_brick_vertical_slab", () -> new EndStoneBrickVerticalSlabBlock());
	public static final RegistryObject<Block> BLACKSTONE_VERTICAL_SLAB = REGISTRY.register("blackstone_vertical_slab", () -> new BlackstoneVerticalSlabBlock());
	public static final RegistryObject<Block> POLISHED_BLACKSTONE_VERTICAL_SLAB = REGISTRY.register("polished_blackstone_vertical_slab", () -> new PolishedBlackstoneVerticalSlabBlock());
	public static final RegistryObject<Block> POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB = REGISTRY.register("polished_blackstone_brick_vertical_slab", () -> new PolishedBlackstoneBrickVerticalSlabBlock());
	public static final RegistryObject<Block> CUT_COPPER_VERTICAL_SLAB = REGISTRY.register("cut_copper_vertical_slab", () -> new CutCopperVerticalSlabBlock());
	public static final RegistryObject<Block> EXPOSED_CUT_COPPER_VERTICAL_SLAB = REGISTRY.register("exposed_cut_copper_vertical_slab", () -> new ExposedCutCopperVerticalSlabBlock());
	public static final RegistryObject<Block> WEATHERED_CUT_COPPER_VERTICAL_SLAB = REGISTRY.register("weathered_cut_copper_vertical_slab", () -> new WeatheredCutCopperVerticalSlabBlock());
	public static final RegistryObject<Block> OXIDIZED_CUT_COPPER_VERTICAL_SLAB = REGISTRY.register("oxidized_cut_copper_vertical_slab", () -> new OxidizedCutCopperVerticalSlabBlock());
	public static final RegistryObject<Block> WAXED_CUT_COPPER_VERTICAL_SLAB = REGISTRY.register("waxed_cut_copper_vertical_slab", () -> new WaxedCutCopperVerticalSlabBlock());
	public static final RegistryObject<Block> WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB = REGISTRY.register("waxed_exposed_cut_copper_vertical_slab", () -> new WaxedExposedCutCopperVerticalSlabBlock());
	public static final RegistryObject<Block> WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB = REGISTRY.register("waxed_weathered_cut_copper_vertical_slab", () -> new WaxedWeatheredCutCopperVerticalSlabBlock());
	public static final RegistryObject<Block> WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB = REGISTRY.register("waxed_oxidized_cut_copper_vertical_slab", () -> new WaxedOxidizedCutCopperVerticalSlabBlock());
	public static final RegistryObject<Block> COBBLED_DEEPSLATE_VERTICAL_SLAB = REGISTRY.register("cobbled_deepslate_vertical_slab", () -> new CobbledDeepslateVerticalSlabBlock());
	public static final RegistryObject<Block> POLISHED_DEEPSLATE_VERTICAL_SLAB = REGISTRY.register("polished_deepslate_vertical_slab", () -> new PolishedDeepslateVerticalSlabBlock());
	public static final RegistryObject<Block> DEEPSLATE_BRICK_VERTICAL_SLAB = REGISTRY.register("deepslate_brick_vertical_slab", () -> new DeepslateBrickVerticalSlabBlock());
	public static final RegistryObject<Block> DEEPSLATE_TILE_VERTICAL_SLAB = REGISTRY.register("deepslate_tile_vertical_slab", () -> new DeepslateTileVerticalSlabBlock());
	public static final RegistryObject<Block> MUD_BRICK_VERTICAL_SLAB = REGISTRY.register("mud_brick_vertical_slab", () -> new MudBrickVerticalSlabBlock());
	public static final RegistryObject<Block> OAKREDROOFTILES = REGISTRY.register("oakredrooftiles", () -> new OakredrooftilesBlock());
	public static final RegistryObject<Block> RUNED_DEEPSLATE_BRICKS_ETA_ON = REGISTRY.register("runed_deepslate_bricks_eta_on", () -> new RunedDeepslateBricksEtaOnBlock());
	public static final RegistryObject<Block> RUNED_DEEPSLATE_BRICKS_ETA_OFF = REGISTRY.register("runed_deepslate_bricks_eta_off", () -> new RunedDeepslateBricksEtaOffBlock());
	public static final RegistryObject<Block> RUNED_DEEPSLATE_BRICKS_GAMMA_ON = REGISTRY.register("runed_deepslate_bricks_gamma_on", () -> new RunedDeepslateBricksGammaOnBlock());
	public static final RegistryObject<Block> RUNED_DEEPSLATE_BRICKS_GAMMA_OFF = REGISTRY.register("runed_deepslate_bricks_gamma_off", () -> new RunedDeepslateBricksGammaOffBlock());
	public static final RegistryObject<Block> RUNED_DEEPSLATE_BRICKS_BETA_OFF = REGISTRY.register("runed_deepslate_bricks_beta_off", () -> new RunedDeepslateBricksBetaOffBlock());
	public static final RegistryObject<Block> RUNED_DEEPSLATE_BRICKS_BETA_ON = REGISTRY.register("runed_deepslate_bricks_beta_on", () -> new RunedDeepslateBricksBetaOnBlock());
	public static final RegistryObject<Block> BURNT_OUT_LANTERN = REGISTRY.register("burnt_out_lantern", () -> new BurntOutLanternBlock());
	public static final RegistryObject<Block> DIRT_SLAB = REGISTRY.register("dirt_slab", () -> new DirtSlabBlock());
	public static final RegistryObject<Block> DIRT_STAIRS = REGISTRY.register("dirt_stairs", () -> new DirtStairsBlock());
	public static final RegistryObject<Block> COAL_FURNACE = REGISTRY.register("coal_furnace", () -> new CoalFurnaceBlock());
}
